import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    borderRadius: 32,
    paddingBottom: 28,
    alignItems: 'center',
    marginVertical: 40,
    width: '95%',
    maxWidth: 600,
    alignSelf: 'center',
    elevation: 8,
  },
  header: {
    width: '100%',
    backgroundColor: '#388E3C',
    paddingVertical: 24,
    paddingHorizontal: 40,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 20,
    marginBottom: 24,
  },
  headerTitle: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  searchRow: {
    flexDirection: 'row',
    width: '90%',
    maxWidth: 500,
    marginVertical: 16,
    alignSelf: 'center',
  },
  searchInput: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 22,
    backgroundColor: '#f4f4f4',
    borderTopLeftRadius: 24,
    borderBottomLeftRadius: 24,
    fontSize: 18,
  },
  searchButton: {
    paddingVertical: 14,
    paddingHorizontal: 28,
    backgroundColor: '#4CAF50',
    borderTopRightRadius: 24,
    borderBottomRightRadius: 24,
    marginLeft: -1,
  },
  authButton: {
    backgroundColor: '#2e7031',
    color: '#fff',
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 28,
    fontSize: 17,
    fontWeight: 'bold',
    marginHorizontal: 8,
  },
  welcomeMsg: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginRight: 8,
  },
  bookmarkBtn: {
    backgroundColor: '#FFD600',
    color: '#222',
    borderRadius: 18,
    paddingVertical: 8,
    paddingHorizontal: 18,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  logoutBtn: {
    backgroundColor: '#388E3C',
    borderColor: '#fff',
    borderWidth: 1.5,
    borderRadius: 18,
    paddingVertical: 8,
    paddingHorizontal: 18,
    color: '#fff',
    fontWeight: 'bold',
    marginLeft: 4,
  },
  mapArea: {
    width: '90%',
    height: 220,
    backgroundColor: '#eafbe7',
    borderRadius: 28,
    marginVertical: 24,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 22,
  },
  inputText: {
    backgroundColor: '#f4f4f4',
    borderRadius: 20,
    paddingVertical: 13,
    paddingHorizontal: 20,
    fontSize: 18,
    marginVertical: 8,
  },
  commonButton: {
    backgroundColor: '#4CAF50',
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 28,
    fontSize: 18,
    fontWeight: 'bold',
    marginVertical: 8,
  },
  randomButton: {
    backgroundColor: '#43A047',
    borderRadius: 24,
    paddingVertical: 16,
    paddingHorizontal: 34,
    fontSize: 20,
    fontWeight: 'bold',
    marginVertical: 10,
  },
  resultMessage: {
    color: '#1976D2',
    backgroundColor: '#eafbe7',
    borderRadius: 18,
    padding: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 20,
    marginVertical: 24,
  },
  restaurantCard: {
    backgroundColor: '#fff',
    borderRadius: 22,
    padding: 22,
    marginBottom: 18,
    shadowColor: '#388E3C',
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 4,
  },
  restaurantTitle: {
    fontSize: 19,
    fontWeight: 'bold',
    marginBottom: 7,
    color: '#111',
  },
  restaurantMeta: {
    color: '#888',
    fontSize: 16,
    marginBottom: 4,
  },
  detailBtn: {
    marginTop: 12,
    padding: 10,
    backgroundColor: '#4CAF50',
    color: '#fff',
    borderRadius: 14,
    fontSize: 16,
    alignSelf: 'flex-end',
  },
});