// css 스타일을 React Native 스타일로 변환

import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    borderRadius: 32,
    paddingBottom: 28,
    alignItems: 'center',
    marginVertical: 40,
    width: '95%',
    maxWidth: 600,
    alignSelf: 'center',
    elevation: 8,
  },
  header: {
    width: '100%',
    backgroundColor: '#white',
    paddingVertical: 24,
    paddingHorizontal: 40,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 20,
    marginBottom: 24,
  },
  headerTitle: {
    color: '#black',
    fontSize: 28,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  searchRow: {
    flexDirection: 'row',
    width: '90%',
    maxWidth: 500,
    marginVertical: 16,
    alignSelf: 'center',
  },
  searchInput: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 22,
    backgroundColor: '#f4f4f4',
    borderTopLeftRadius: 24,
    borderBottomLeftRadius: 24,
    fontSize: 18,
  },
  searchButton: {
    paddingVertical: 14,
    paddingHorizontal: 28,
    backgroundColor: '#4CAF50',
    borderTopRightRadius: 24,
    borderBottomRightRadius: 24,
    marginLeft: -1,
  },
  authButton: {
    backgroundColor: '#2e7031',
    color: '#fff',
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 28,
    fontSize: 17,
    fontWeight: 'bold',
    marginHorizontal: 8,
  },
  welcomeMsg: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginRight: 8,
  },
  bookmarkBtn: {
    backgroundColor: '#FFD600',
    color: '#222',
    borderRadius: 18,
    paddingVertical: 8,
    paddingHorizontal: 18,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  logoutBtn: {
    backgroundColor: '#388E3C',
    borderColor: '#fff',
    borderWidth: 1.5,
    borderRadius: 18,
    paddingVertical: 8,
    paddingHorizontal: 18,
    color: '#fff',
    fontWeight: 'bold',
    marginLeft: 4,
  },
  mapArea: {
    width: '90%',
    height: 220,
    backgroundColor: '#eafbe7',
    borderRadius: 28,
    marginVertical: 24,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 22,
  },
  inputText: {
    backgroundColor: '#f4f4f4',
    borderRadius: 20,
    paddingVertical: 13,
    paddingHorizontal: 20,
    fontSize: 18,
    marginVertical: 8,
  },
  commonButton: {
    backgroundColor: '#4CAF50',
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 28,
    fontSize: 18,
    fontWeight: 'bold',
    marginVertical: 8,
  },
  randomButton: {
    backgroundColor: 'black',
    borderRadius: 24,
    paddingVertical: 16,
    paddingHorizontal: 34,
    fontSize: 20,
    fontWeight: 'bold',
    marginVertical: 10,
  },
  resultMessage: {
    color: '#1976D2',
    backgroundColor: '#eafbe7',
    borderRadius: 18,
    padding: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 20,
    marginVertical: 24,
  },
  restaurantCard: {
    backgroundColor: '#fff',
    borderRadius: 22,
    padding: 22,
    marginBottom: 18,
    shadowColor: '#388E3C',
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 4,
  },
  restaurantTitle: {
    fontSize: 19,
    fontWeight: 'bold',
    marginBottom: 7,
    color: '#111',
  },
  restaurantMeta: {
    color: '#888',
    fontSize: 16,
    marginBottom: 4,
  },
  detailBtn: {
    marginTop: 12,
    padding: 10,
    backgroundColor: '#4CAF50',
    borderRadius: 14,
    alignSelf: 'flex-end',
  },
  detailText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },

  // 그리드 아이템 컨테이너
  cardContainer: {
    flex: 1,
    padding: 8,
  },
  // 개별 카드 스타일
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 12,
    margin: 4,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  // 북마크 표시(카드 테두리)
  bookmarked: {
    borderColor: '#FFD600',
    borderWidth: 2,
  },
  // 즐겨찾기 버튼 위치 및 스타일
  starBtn: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#DDD',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  starActive: {
    backgroundColor: '#FFD600',
    borderColor: '#FFD600',
  },
  // 모드 토글 버튼
  toggleContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 12,
  },
  toggleBtn: {
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#f4f4f4',
    marginHorizontal: 8,
  },
  toggleActive: {
    backgroundColor: '#43A047',
  },
  toggleText: {
    fontSize: 14,
    color: '#555',
  },
  toggleTextActive: {
    color: '#fff',
    fontWeight: 'bold',
  },
});
export const stylesNative = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 32,
    paddingBottom: 28,
    alignItems: 'center',
    marginVertical: 40,
    width: '95%',
    maxWidth: 600,
    alignSelf: 'center',
    elevation: 8,
  },
  mapArea: {
    width: '90%',
    height: 220,
    backgroundColor: '#eafbe7',
    borderRadius: 28,
    marginVertical: 24,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 22,
  },
});